name: Update AGH
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths-ignore:
  schedule:
    - cron: '15 15 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Build blocklist
        uses: actions/checkout@v3
      - run: |
          sudo npm i -g @adguard/hostlist-compiler
          hostlist-compiler -c 1.json -o blocklist-agh.txt
          hostlist-compiler -c 2.json -o adultfilter-agh.txt
          hostlist-compiler -c 3.json -o familyfilter-agh.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "AGH"
          git push
